### ISSUE TITLE
Integrate/Mention workaround for the use of glossing inside footnotes or similar environments

### ISSUE THREAD

**Issue by simon-clematide** [jspitz/covington#1]
There is a workaround on 
[stackexchange](http://tex.stackexchange.com/questions/169740/covington-example-in-footnote)
on how to make the glossing makros work in footnotes or similar environments (e.g. [baposter]( http://www.brian-amberg.de/uni/poster/)

BTW, it is important to note that each gloss `\gll` needs its own `\xx` opener.

**Comment by jspitz** [comment]
I have committed a solution inspired by David's suggestion, introducing new macros `\xgll`, `\xglll` and `\xgle`. Your example file would now read:
```
\documentclass{article}
\usepackage{covington}

\begin{document}
Some text.\footnote{This is commented with an example:

\begin{example}
\xgll qaama l-qawm-u illaa zayd-an\xgle
       stood.up DEF-people but zayd-ACC\xgle
\glt `Everyone stood up except for Zayd'
\glend
\end{example}

\begin{example}
This is an unglossed example.
\end{example}
}
\end{document}
```
Could you please test the development version?

**Comment by simon-clematide** [comment]
Tested with footnotes and baposter environment.  Works.
One question: Would it not make sense the put the x at the end? E.g. gllx glex

**Comment by jspitz** [comment]
I think as a prefix, the 'x' is more noticeable.

I'll push a new version to CTAN soon.

**Comment by simon-clematide** [comment]
Yes, that makes sense. Thanks a lot for integrating this so quickly.
