### ISSUE TITLE
Improper alignment in subexamples with chapter numbering

### ISSUE THREAD

**Issue by clarino** [jspitz/covington#11]
With chapter numbering, e.g. (2.13), the second subexample doesn't properly align with the first one if the number has double digits.

<img width="450" alt="Screen Shot 2022-02-19 at 06 29 51" src="https://user-images.githubusercontent.com/1823311/154787800-c9b4609f-61f6-4a37-8ba0-4961b5df2ba3.png">

**Comment by jspitz** [comment]
This cannot be adjusted automatically. Please adjust `\subexamplenumbersep` as documented in the manual, sec. 3.4.
