### ISSUE TITLE
How to set up a separate numbering in footnote?

### ISSUE THREAD

**Issue by evadatou** [jspitz/covington#12]
How can I make it automatically use a separate numbering in footnote, for instance, I want the examples in the footnotes to be continuously listed in roman numbers (i), (ii), (iii). Thank you in advance!

**Comment by jspitz** [comment]
Quick and dirty:
```tex
\makeatletter
\newif\ifinfootnote\infootnotefalse
\let\origfootnotetext\@footnotetext
\long\def\@footnotetext#1{\infootnotetrue\origfootnotetext{#1}\infootnotefalse}

\newcounter{fnex}[footnote]
\renewcommand{\thefnex}{\roman{fnex}}

\renewenvironment{covexamples}%
{%
	\begin{list}{\covexamplenofs\covexnumber{\ifinfootnote\thefnex\else\@@exampleno\fi}}%
		{%
			\addtolength{\labelwidth}{\examplenumbersep}%
			\addtolength{\leftmargin}{\examplenumbersep}%
			\addtolength{\leftmargin}{\exampleind}%
			\ifinfootnote
			  \setcounter{covexsave}{\arabic{fnex}}%
			  \usecounter{fnex}%
			  \setcounter{fnex}{\arabic{covexsave}}%
			\else
			  \ifownexcounter
			    \setcounter{covexsave}{\arabic{covex}}%
			    \usecounter{covex}%
			    \setcounter{covex}{\arabic{covexsave}}%
			  \else
			    \setcounter{covexsave}{\arabic{equation}}%
			    \usecounter{equation}%
			    \setcounter{equation}{\arabic{covexsave}}%
			  \fi
			\fi
			\setlength{\listparindent}{0pt}%
			\def\makelabel##1{##1\hfil}%
		}%
		\raggedright\covexamplefs}%
	{\end{list}}
\makeatother
```

**Comment by jspitz** [comment]
Changing
`\newcounter{fnex}[footnote]`
to
`\newcounter{fnex}`
should do it.

**Comment by jspitz** [comment]
The next version will feature an option `ownfncounter` which adds a continuous roman counter within footnotes and an option `resetownfncounter` which will reset this counter at each footnote.

**Comment by jspitz** [comment]
> The next version will feature an option `ownfncounter` which adds a continuous roman counter within footnotes and an option `resetownfncounter` which will reset this counter at each footnote.

Now renamed to `ownfncounter` (not reset) and `ownfncounter*` (reset).

**Comment by evadatou** [comment]
That’s great! Thank you!

**Comment by jspitz** [comment]
V. 2.8 with this feature has just been uploaded to CTAN.
