### ISSUE TITLE
Adding the quotation marker for translation by myself with /digloss{}{}{}

### ISSUE THREAD

**Issue by evadatou** [jspitz/covington#15]
Hi, is there a way that I can add the quotation by myself when I use the /digloss{}{}{} function? This will be particularly helpful in examples in which I need to add literal meaning and the real translation of the example.
Lun dao ni le 
turn RST 2SG PST        
Lit.: 'Turned to you'
'It's your turn.'

or when I need to specify the language at the end of the example (same line as the translation)
Lun dao ni le 
turn RST 2SG PST        
Lit.: 'Turned to you'
'It's your turn.'                       [Chinese]

Thanks!

**Comment by jspitz** [comment]
Sure:
```tex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}
\usepackage{covington}
\usepackage{csquotes}
\begin{document}
	
	\digloss[enquotetl=false]
	        {Lun dao ni le}
	        {turn RST 2SG PST}
	        {Lit.: \lmean{Turned to you}\\
	        \lmean{It's your turn.} [Chinese]}

\end{document}
```
![grafik](https://github.com/jspitz/covington/assets/4538783/784a36cc-68dc-4941-9b7d-b2dce71cc5ea)
