### ISSUE TITLE
\twoacc fails in bibliography

### ISSUE THREAD

**Issue by keithbriggs** [jspitz/covington#2]
\twoacc is no longer compatible with the latest biber, meaning that it cannot be used in book or article titles. 

See:
https://tex.stackexchange.com/questions/370788/twoacc-fails-in-bibliography

**Comment by jspitz** [comment]
Thanks for the report, but AFAIU the stackexchange thread, this is something that should be fixed in `biber` rather than in `covington`. Could you please bring the issue to the attention of the `biber` developers?

**Comment by keithbriggs** [comment]
Ok, I'll do that, but would there be any value in also adding a new, more conventional syntax to covington, e.g, \twoaccent{\u}{\=}{y}, while still keeping the old one?

**Comment by jspitz** [comment]
The next version will introduce a new macro `\twodias` with three arguments. `\twoacc` is kept for backwards compatibilty.
