### ISSUE TITLE
\textfloatsep should not be overwritten OR provide a package options to set or bypass setting it

### ISSUE THREAD

**Issue by flueterflam** [jspitz/covington#3]
Not sure if it's relevant, but I am using `memoir` primarily.

I just ran into an issue where setting all the `memoir` settings indicated that something was overwriting my `\textfloatsep` length (`\setlength{\textfloatsep}{0pt}`).  I narrowed this down to `covington` package after a bit of work.

The space above/below an `example` , `examples`, and `exercise` environments should IMHO either follow the uniformity of the length that the user sets for the entire document *or* only apply to these `covington` environments.  0.7in is quite large and shouldn't be forced upon users against their wishes for `\textfloatsep` in *all other* floats.

It's also unclear to me why `covington` needs to overwrite this length.  While true that I can set this length again *after* `covington` is loaded, it was unexpected and I prefer to keep certain preamble definitions together (in this case, for `memoir`), some of which require loading very early due to package dependencies.

Seems there are several options to support users like me, or in general:

1. Add a package option to disable setting `\textfloatsep`
2. Add a package option to specify the length for `\textfloatsep`
3. Calculate the difference between `\textfloatsep` and 0.7in - place this vertical white space difference at the top and bottom of any `covington` environments

These option, I believe, should support backwards compatibility.  There may be option options as well?

Thanks in advance for considering this!

**Comment by jspitz** [comment]
Thank you for the report. I agree covington should not touch this. It also sets `\raggedbottom`, which is not necessary.

I suspect the reason is that this package initially was a personal macro collection of Michael's. I now added a general option `keeplayout` to opt-out these presettings.

Could you please test and report back?

**Comment by flueterflam** [comment]
Just got a chance to test out the change.  Downloaded the update and `keeplayout` works great for me!  Thanks for getting to this so quickly!

**Comment by jspitz** [comment]
Thanks for testing. Covington 1.5. has just been submitted to CTAN.
