### ISSUE TITLE
Code to keep first line of glosss from being interlinearized

### ISSUE THREAD

**Issue by lingdoc** [jspitz/covington#4]
For various linguistic documents I've used the following code in the preamble of LyX in order to keep the Covington interlinearized examples from interlinearizing the first line:

```
{\catcode`\^^M=12 \endlinechar=-1 % 12 = other
\gdef\threesent#1^^M#2^^M#3^^M % #1 = first line, #2 = second line, #3 = third
    {\eachwordone#1\newline%
     \getwords(\linetwo,\eachwordtwo)#2 ^^M%
     \getwords(\linethree,\eachwordthree)#3 ^^M%
     \loop\lastword{\eachwordtwo}{\linetwo}{\wordtwo}%
          \lastword{\eachwordthree}{\linethree}{\wordthree}%
          \global\setbox\gline=\hbox{\unhbox\gline
                                     \hskip\glossglue
                                     \vtop{\box\lineone%\wordone   % vtop was vbox
                                           \nointerlineskip
                                           \box\wordtwo
                                           \nointerlineskip
                                           \box\wordthree
                                          }%
                                    }%
          \testdone
          \ifnotdone
     \repeat
     \egroup % matches \bgroup in \gloss
    }
}
```
This works in LyX 2.3.0, but my friend who used the same code in his document has a more recent version of LyX. The same file produces a pdf with correct output for me (first line of IGT not interlinearized) but not for him (first line of IGT interlinearized with other lines). This suggests that the issue is how LyX 2.3.3 handles gloss definitions, so I thought I would open this issue to get your recommendations on what needs to change in the redefinition code to fix it for the LyX 2.3.3 preamble.

I had a look through the Covington style code and I can't quite see where the mismatch in the redefinitions are.. appreciate your feedback.

**Comment by jspitz** [comment]
The reason why it has no effect in LyX 2.3 is that covington is loaded after the user preamble, so your definition of \threesent is overwritten by covington.
I don't really understand what you're trying to achieve with that, but it strikes me a three line gloss is not the right tool for this. Why don't you use an example line and add a two line gloss below?

In any case, this is not a bug in the covington package.

**Comment by jspitz** [comment]
(and just to explain why covington is loaded later now: This solves a loading order conflict with beamer-article)

**Comment by lingdoc** [comment]
ah, ok, that makes sense, thanks. so to overwrite the Covington code in LyX, can I insert this as ERT at the beginning of the document?

To clarify, this is particularly useful when writing a grammatical description for little-known languages where there is a difference between the local orthographic form and the IPA. including IPA is most helpful for other linguists, but not particularly helpful for the language community. Using this convention allows multiple parties to benefit from the grammatical description.

Using an example line and a two-line gloss results in some weird formatting issues on multiple (non-obvious) pages when compiling such large (400+ page) documents.

**Comment by jspitz** [comment]
It probably won't work to redef at the beginning of a document. Using `\AtBeginDocument` is normally the way to go.
As to the formatting issues, I would be interested to see them.

**Comment by lingdoc** [comment]
when I use `\AtBeginDocument` to enclose the code in the preamble, I get the following error (among others):

```! Illegal parameter number in definition of \threesent.```

I'll see if I can post some of the formatting errors with example + two-line gloss, though it might not be possible, given that I spent several days/weeks to fix this problem when I was writing my thesis four years ago, and I've gone through several computers since then. One formatting error I can think of off the top of my head (which should be relatively easy to demonstrate) is that the preceding text in your recommendation is not kept with the next lines and splits the examples over pages, which is problematic. With Covington linguistic glossed examples, you can prevent this with the following code for four-line glosses, which makes the code I posted above behave correctly AND stay together without breaking across pages (as long as it fits within 4 lines).

```\let\oldlingglosss\lingglosss
\let\endoldlingglosss\endlingglosss
\renewenvironment{lingglosss}{%
\needspace{4\baselineskip}
\begin{oldlingglosss}%
}
{
\end{oldlingglosss}
}
```

This also allows for nicely formatted appendices of texts. Below is a page from [my thesis](https://www.academia.edu/11943811/A_Grammar_of_Pnar) illustrating this. I also made some formatting changes to the `\eachwordone`, `\eachwordtwo`, and `\eachwordthree` commands, but this shouldn't effect whether the above code works, right?
[Appendix_page.pdf](https://github.com/jspitz/covington/files/3147804/Appendix_page.pdf)

I suppose the other workaround would be to edit a local copy of Covington directly with this code, or maybe to add another type of `linggloss` to the package. In the meantime I might just recommend to my friend that he downgrade to LyX 2.3.0 from 2.3.2 (I was incorrect about his version number in my first post), since he submits his thesis in just a few weeks.

**Comment by jspitz** [comment]
> when I use `\AtBeginDocument` to enclose the code in the preamble, I get the following error (among others):
> 
> `! Illegal parameter number in definition of \threesent.`

OK, then the catcode change confused the hook. Another workaround is to add to Document > Settings > Local Layout:

`Provides covington 1`

and then load covington manually in the preamble, before this code chunk.

> One formatting error I can think of off the top of my head (which should be relatively easy to demonstrate) is that the preceding text in your recommendation is not kept with the next lines and splits the examples over pages, which is problematic. 

You can easily workaround this in LyX by packing everything into a minipage (or parbox). 

> I suppose the other workaround would be to edit a local copy of Covington directly with this code, or maybe to add another type of `linggloss` to the package. In the meantime I might just recommend to my friend that he downgrade to LyX 2.3.0 from 2.3.2

In the long term, if this kind of gloss usage is common, I might just add a new low level command to covington which lets you add such preceding text without hacking the gloss environment. E.g.

```
\glp Some preceding text that is not interlinearized
\gll Dit is een Nederlands voorbeeld.
     This is a Dutch example.
\glt ‘This is an example in Dutch.’
\glend
```
and in the new interface:

```
\digloss[preamble={Some preceding text that is not interlinearized}]
{Dit is een Nederlands voorbeeld}
{This is a Dutch example}
{This is an example in Dutch.}
```

Would that make sense for your usecase?

**Comment by lingdoc** [comment]
> Would that make sense for your usecase?

Yes, that should be fine. It is probably not a particularly common usage, though I think it is helpful to the language community if they were to read a grammatical description.

I'll try getting it to work in the meantime with the `Provides covington 1` workaround.

**Comment by jspitz** [comment]
Version 2.1 of `covington` which introduces this feature has just been uploaded to CTAN.

**Comment by lingdoc** [comment]
ok, thanks. I'll give it a try.
