### ISSUE TITLE
glossed examples not working with beamer

### ISSUE THREAD

**Issue by lingdoc** [jspitz/covington#6]
The LyX wiki says that Covington and Beamer should work together pretty much out of the box (https://wiki.lyx.org/LyX/LinguistLyX#toc15) since 2.2.1, and since I'm now using 2.3 I thought I'd try it out. I created a new Beamer presentation and I get a bunch of errors when compiling, such as:
`! Paragraph ended before \twosent was complete.`
`! LaTeX Error: \begin{flushleft} on input line 50 ended by \end{beamer@framepauses}.`
etc.

I'm including a MWE below in case you can see what the issue is (rename the extension to `.lyx` to open it). Weirdly, it compiles fine when I delete the glosse environment, but throws all sorts of errors when I put it in.
[Beamer_examples.txt](https://github.com/jspitz/covington/files/3525103/Beamer_examples.txt)

If you have a Beamer/Covington template that LyX users could use and that works, maybe you could put it up on the wiki so I can figure out what I'm doing wrong.

**Comment by jspitz** [comment]
You need a "fragile" frame for glosses, See Help > Specific Manuals > Linguistics, section "Glosses", "Tips & Tricks", and also the Wiki page you referred to ("Using covington (glosses and examples) in a beamer presentation")

**Comment by jspitz** [comment]
Corrected example
[Beamer_examples.lyx.txt](https://github.com/jspitz/covington/files/3525337/Beamer_examples.lyx.txt)

**Comment by lingdoc** [comment]
thanks! I must have missed that slight detail.
